/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.projektet;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author oskarjolesjo
 */
public class AdminInloggning extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form AdminInloggning
     */
    public AdminInloggning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminInlogg = new javax.swing.JLabel();
        txtEpost = new javax.swing.JLabel();
        txtLösenord = new javax.swing.JLabel();
        angeLosenord = new javax.swing.JPasswordField();
        angeEpost = new javax.swing.JTextField();
        btnLoggaIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdminInlogg.setText("Administratör Inloggning");

        txtEpost.setText("Epost");

        txtLösenord.setText("Lösenord");

        angeLosenord.setText("jPasswordField1");

        angeEpost.setColumns(5);

        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(lblAdminInlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLösenord)
                    .addComponent(txtEpost))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoggaIn)
                    .addComponent(angeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAdminInlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpost)
                    .addComponent(angeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLösenord)
                    .addComponent(angeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoggaIn)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        // TODO add your handling code here:

        String epost = angeEpost.getText();
        char[] charLosenord = angeLosenord.getPassword();
        String losenord = new String(charLosenord);

        try {
            String sqlFraga = "SELECT losenord FROM agent WHERE Epost = '" + epost + "'";
            String getAgentID = "SELECT Agent_ID FROM agent WHERE Epost = '" + epost + "'";
            String agentID = idb.fetchSingle(getAgentID);
            String sqlFragaAdmin = "SELECT Administrator FROM agent WHERE Agent_ID = " + agentID;
            String sqlSvarLosenord = idb.fetchSingle(sqlFraga);
            String sqlSvarAdmin = idb.fetchSingle(sqlFragaAdmin);

            if (sqlSvarLosenord != null && losenord.equals(sqlSvarLosenord) && sqlSvarAdmin.equals("J")) {
                dispose();
                new AdminStartsida(idb).setVisible(true);
            } else if (sqlSvarLosenord != null && losenord.equals(sqlSvarLosenord) && sqlSvarAdmin.equals("N")) {
                JOptionPane.showMessageDialog(null, "Du är inte en administratör.");
            } else {
                JOptionPane.showMessageDialog(null, "E-post eller lösenord är felaktigt.");
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());
        }

    }//GEN-LAST:event_btnLoggaInActionPerformed

//private boolean validateLogin(String epost, String losenord) {
//    boolean resultat = false;
//    
//    String query = "SELECT * FROM Anvandare WHERE Epost = '" + epost + "' AND Losenord = '" + losenord + "'";
//    
//    
//    if(epost == ao@mib.net && losenord == planka){
//        resultat = true;
//    }
//    
//    
//    
//    
//    return resultat; 
//}
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angeEpost;
    private javax.swing.JPasswordField angeLosenord;
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel lblAdminInlogg;
    private javax.swing.JLabel txtEpost;
    private javax.swing.JLabel txtLösenord;
    // End of variables declaration//GEN-END:variables
}
