/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.projektet;

import java.util.HashMap;
import javax.swing.JOptionPane;
//import oru.inf.InfDB;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author danie
 */
public class AgentInloggning extends javax.swing.JFrame {

    private InfDB idb;
    private HashMap<String, String> anvandare;

    /**
     * Creates new form Inloggning
     */
    public AgentInloggning(InfDB idb) {
        initComponents();
        this.idb = idb;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoggaIn = new javax.swing.JButton();
        txtValkommen = new javax.swing.JTextField();
        angeLosenord = new javax.swing.JPasswordField();
        lblLosenord = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        angeEpost = new javax.swing.JTextField();
        lblFelmeddelande = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        txtValkommen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValkommen.setText("Inloggning Agent");
        txtValkommen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValkommenActionPerformed(evt);
            }
        });

        angeLosenord.setColumns(10);
        angeLosenord.setText("jPasswordField1");
        angeLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angeLosenordActionPerformed(evt);
            }
        });

        lblLosenord.setText("Lösenord:");

        lblEpost.setText("E-post:");

        angeEpost.setColumns(10);
        angeEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angeEpostActionPerformed(evt);
            }
        });

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(angeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLosenord)
                                    .addGap(18, 18, 18)
                                    .addComponent(angeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnLoggaIn))
                        .addGap(201, 201, 201))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(txtValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLoggaIn)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValkommenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValkommenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValkommenActionPerformed

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        String epost = angeEpost.getText();
        char[] charLosenord = angeLosenord.getPassword();
        String losenord = new String(charLosenord);

        if (Validering.kollaTomRuta(angeEpost) && (Validering.kollaTomRuta2(angeLosenord)))

        try {
            String sqlFraga = "SELECT losenord FROM agent WHERE Epost = '" + epost + "'";
            String getAgentID = "SELECT Agent_ID FROM agent WHERE Epost = '" + epost + "'";
            String agentID = idb.fetchSingle(getAgentID);
            String sqlFragaAdmin = "SELECT Administrator FROM agent WHERE Agent_ID = " + agentID;
            String sqlSvarLosenord = idb.fetchSingle(sqlFraga);
            String sqlSvarAdmin = idb.fetchSingle(sqlFragaAdmin);

            if (sqlSvarLosenord != null && losenord.equals(sqlSvarLosenord) && sqlSvarAdmin.equals("N")) {
                dispose();
                new AgentStartsida(idb, agentID).setVisible(true);
            } else if (sqlSvarLosenord != null && losenord.equals(sqlSvarLosenord) && sqlSvarAdmin.equals("J")) {
                JOptionPane.showMessageDialog(null, "Du är en administratör, byt inloggning till administratör.");
            } else {
                JOptionPane.showMessageDialog(null, "E-post eller lösenord är felaktigt.");
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());
        }


    }//GEN-LAST:event_btnLoggaInActionPerformed

    private void angeLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angeLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angeLosenordActionPerformed

    private void angeEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angeEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angeEpostActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angeEpost;
    private javax.swing.JPasswordField angeLosenord;
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JTextField txtValkommen;
    // End of variables declaration//GEN-END:variables

}
