/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.projektet;

import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author oskarjolesjo
 */
public class infoTopLista extends javax.swing.JFrame {
private InfDB idb;
    /**
     * Creates new form infoTopLista
     */
    public infoTopLista(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        svealand = new javax.swing.JButton();
        norrland = new javax.swing.JButton();
        gotaland = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textRuta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ITF Devanagari", 1, 24)); // NOI18N
        jLabel1.setText("Visa Topplista för Agenter i angivet område");

        jLabel2.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel2.setText("Välj område:");

        svealand.setText("Svealand");
        svealand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svealandActionPerformed(evt);
            }
        });

        norrland.setText("Norrland");
        norrland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norrlandActionPerformed(evt);
            }
        });

        gotaland.setText("Götaland");
        gotaland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotalandActionPerformed(evt);
            }
        });

        textRuta.setColumns(20);
        textRuta.setRows(5);
        jScrollPane1.setViewportView(textRuta);

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(svealand)
                        .addGap(18, 18, 18)
                        .addComponent(norrland)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gotaland)))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(svealand)
                    .addComponent(norrland)
                    .addComponent(gotaland))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotalandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotalandActionPerformed
        textRuta.setText("");

        ArrayList<String> allaAgenter;

        try {
            String sqlFraga = "SELECT agent.namn, COUNT(*) as alien_count FROM agent JOIN alien ON agent.agent_id = alien.ansvarig_agent where omrade = 2 group by agent.namn order by alien_count desc limit 3";
            allaAgenter = idb.fetchColumn(sqlFraga);

            for (String agentNamn : allaAgenter) {
                textRuta.append(agentNamn + "\n");
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());

        }


    }//GEN-LAST:event_gotalandActionPerformed

    private void svealandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svealandActionPerformed
        textRuta.setText("");

        ArrayList<String> allaAgenter;

        try {
            String sqlFraga = "SELECT agent.namn, COUNT(*) as alien_count FROM agent JOIN alien ON agent.agent_id = alien.ansvarig_agent where omrade = 1 group by agent.namn order by alien_count desc limit 3";
            allaAgenter = idb.fetchColumn(sqlFraga);

            for (String agentNamn : allaAgenter) {
                textRuta.append(agentNamn + "\n");
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());

        }


    }//GEN-LAST:event_svealandActionPerformed

    private void norrlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norrlandActionPerformed
        textRuta.setText("");

        ArrayList<String> allaAgenter;

        try {
            String sqlFraga = "SELECT agent.namn, COUNT(*) as alien_count FROM agent JOIN alien ON agent.agent_id = alien.ansvarig_agent where omrade = 4 group by agent.namn order by alien_count desc limit 3";
            allaAgenter = idb.fetchColumn(sqlFraga);

            for (String agentNamn : allaAgenter) {
                textRuta.append(agentNamn + "\n");
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());

        }


    }//GEN-LAST:event_norrlandActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gotaland;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton norrland;
    private javax.swing.JButton svealand;
    private javax.swing.JTextArea textRuta;
    // End of variables declaration//GEN-END:variables
}
