/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.projektet;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author oskarjolesjo
 */
public class uppdateraAlien extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form uppdateraAgent
     */
    public uppdateraAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboAlien = new javax.swing.JComboBox<>();
        regdatum = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        namn = new javax.swing.JTextField();
        telefon = new javax.swing.JTextField();
        plats = new javax.swing.JTextField();
        losenord = new javax.swing.JTextField();
        ansvarigAgent = new javax.swing.JTextField();
        visaUppgifter = new javax.swing.JButton();
        uppdateraAlien = new javax.swing.JButton();
        nuvarandeAlienID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboboxRas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        uppdateraRas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Uppdatera Alien");

        jLabel3.setText("Reg-Datum");

        jLabel4.setText("Lösenord");

        jLabel5.setText("Namn");

        jLabel6.setText("Telefon");

        jLabel7.setText("Plats");

        jLabel8.setText("Ansvarig Agent ID");

        jLabel9.setText("Välj Alien");

        regdatum.setColumns(8);
        regdatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regdatumActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField2");

        namn.setColumns(8);

        telefon.setColumns(8);

        plats.setColumns(8);

        losenord.setColumns(8);

        ansvarigAgent.setColumns(8);

        visaUppgifter.setText("Visa Uppgifter");
        visaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaUppgifterActionPerformed(evt);
            }
        });

        uppdateraAlien.setText("Uppdatera Alien");
        uppdateraAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppdateraAlienActionPerformed(evt);
            }
        });

        nuvarandeAlienID.setText("Nuvarande ID");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboboxRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Worm", "Squid", "Boglodite" }));
        comboboxRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxRasActionPerformed(evt);
            }
        });

        jLabel2.setText("Välj ras");

        uppdateraRas.setText("Uppdatera ras");
        uppdateraRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppdateraRasActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel10.setText("Uppdatera Ras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ansvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addComponent(uppdateraAlien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uppdateraRas)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jButton1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(namn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(losenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(regdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(258, 258, 258))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(comboAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nuvarandeAlienID)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(visaUppgifter))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(67, 67, 67)
                                .addComponent(comboboxRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(232, 232, 232))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(960, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(visaUppgifter)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuvarandeAlienID)
                        .addGap(7, 7, 7)
                        .addComponent(comboAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(regdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(losenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(namn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(plats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ansvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uppdateraRas)
                                .addGap(64, 64, 64))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(uppdateraAlien)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regdatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regdatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regdatumActionPerformed

    private void visaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaUppgifterActionPerformed
        nuvarandeAlienID.setText("");
        regdatum.setText("");
        telefon.setText("");
        namn.setText("");
        plats.setText("");
        losenord.setText("");
        ansvarigAgent.setText("");
        ArrayList<HashMap<String, String>> soktaAliens;

        try {
            String valdAlien = comboAlien.getSelectedItem().toString();
            String sqlFraga = "SELECT * FROM alien WHERE alien.Namn = '" + valdAlien + "'";
            soktaAliens = idb.fetchRows(sqlFraga);

            for (HashMap<String, String> alien : soktaAliens) {
                nuvarandeAlienID.setText(alien.get("Alien_ID"));
                regdatum.setText(alien.get("Registreringsdatum"));
                telefon.setText(alien.get("Telefon"));
                namn.setText(alien.get("Namn"));
                plats.setText(alien.get("Plats"));
                losenord.setText(alien.get("Losenord"));
                ansvarigAgent.setText(alien.get("Ansvarig_Agent"));

            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());
        }
    }//GEN-LAST:event_visaUppgifterActionPerformed

    private void uppdateraAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppdateraAlienActionPerformed
            try {
        String alienID = nuvarandeAlienID.getText();
        String nyttRegDatum = regdatum.getText();
        String nyTelefon = telefon.getText();
        String nyttNamn = namn.getText();
        String nyPlats = plats.getText();
        String nyttLosenord = losenord.getText();
        String nyttAnsvarigAgent = ansvarigAgent.getText();
       

        
        if (!Validering.agentFinnsIDatabas(idb, nyttAnsvarigAgent)) {
    JOptionPane.showMessageDialog(this, "Ogiltig ansvarig agent. Agenten finns inte i databasen.");
    return;
}

        String sqlFraga = "UPDATE alien SET Registreringsdatum = '" + nyttRegDatum + "', Telefon = '" + nyTelefon + "', Namn = '" + nyttNamn + "', Plats = '" + nyPlats + "', Losenord = '" + nyttLosenord + "', Ansvarig_Agent = '" + nyttAnsvarigAgent + "' WHERE Alien_ID = " + alienID;
        idb.update(sqlFraga);

        SimpleDateFormat datumFormat = new SimpleDateFormat("yyyy-MM-dd");
        datumFormat.parse(nyttRegDatum);
        datumFormat.setLenient(false);

        if (!Validering.valideraTelefonnummer(nyTelefon)) {
            JOptionPane.showMessageDialog(this, "Telefonnummer kan endast innehålla siffror.");
            return;
        }
        if (!Validering.valideraOmradeID(nyPlats)) {
            JOptionPane.showMessageDialog(this, "Ogiltigt omradeID. Endast 1 = Svealand, 2 = Götaland eller 4 = Norrland är tillåtna.");
            return;
        }
        if (!Validering.agentFinnsIDatabas(idb, nyttAnsvarigAgent)) {
            JOptionPane.showMessageDialog(this, "Ogiltig ansvarig agent. Agenten finns inte i databasen.");
            return;
        }
         



        JOptionPane.showMessageDialog(null, "Alien har uppdaterats.");

    } catch (InfException e) {
        System.out.println("Fel: " + e.getMessage());
    } catch (ParseException ex) {
        JOptionPane.showMessageDialog(this, "Ange datum i rätt format, yyyy-MM-dd!");
    }
    }//GEN-LAST:event_uppdateraAlienActionPerformed

    
    private void taBortRad(String alienID) {
    try {
        // Ta bort rad från tabellen boglodite
        String sqltaBortBoglodite = "DELETE FROM boglodite WHERE Alien_ID = '" + alienID + "'";
        idb.delete(sqltaBortBoglodite);

        // Ta bort rad från tabellen squid
        String sqltaBortSquid = "DELETE FROM squid WHERE Alien_ID = '" + alienID + "'";
        idb.delete(sqltaBortSquid);

        // Ta bort rad från tabellen worm
        String sqltaBortWorm = "DELETE FROM worm WHERE Alien_ID = '" + alienID + "'";
        idb.delete(sqltaBortWorm);

       
    } catch (InfException e) {
        System.out.println("Fel: " + e.getMessage());
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboboxRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxRasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxRasActionPerformed

    private void uppdateraRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppdateraRasActionPerformed
        
        String alienID = nuvarandeAlienID.getText();
        

        
        try{ 
//Koden nedan byter ut en aliens ras-tillhörighet ifall denna ska uppdateras
         //Påkallar metoden taBortRad som raderar en rad i den ras-tabell som vald Alien just nu tillhör
         taBortRad(alienID);

        if (comboboxRas.getSelectedItem().toString().equals("Worm")) {
            String egenskaper = JOptionPane.showInputDialog(this, "Ange längden på Alien av ras Worm: ");
            String sqlInsertWorm = "INSERT INTO worm (Alien_ID, Langd) VALUES ('" + alienID + "', '" + egenskaper + "')";
            idb.insert(sqlInsertWorm);
            
        } else if (comboboxRas.getSelectedItem().toString().equals("Squid")) {
            String egenskaper = JOptionPane.showInputDialog(this, "Ange antal armar på Alien av ras Squid: ");
            String sqlInsertSquid = "INSERT INTO squid (Alien_ID, Antal_Armar) VALUES ('" + alienID + "', '" + egenskaper + "')";
            idb.insert(sqlInsertSquid);
            
        } else if (comboboxRas.getSelectedItem().toString().equals("Boglodite")) {
            String egenskaper = JOptionPane.showInputDialog(this, "Ange antal boogies på Alien av ras Boglodite (float-tal):");
            String sqlInsertBoglodite = "INSERT INTO boglodite (Alien_ID, Antal_Boogies) VALUES ('" + alienID + "', '" + egenskaper + "')";
            idb.insert(sqlInsertBoglodite);
            
        }
        
        JOptionPane.showMessageDialog(null, "Alien har uppdaterats.");
        }
        catch(InfException e) {
            System.out.println("fel" + e.getMessage());
        }
        
    }//GEN-LAST:event_uppdateraRasActionPerformed

    /**
     * @param args the command line arguments
     */
    private void fyllCombo() {
        String sqlFraga = " SELECT namn from alien";
        ArrayList<String> allaAlien;

        try {
            allaAlien = idb.fetchColumn(sqlFraga);

            for (String alien : allaAlien) {
                comboAlien.addItem(alien);
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansvarigAgent;
    private javax.swing.JComboBox<String> comboAlien;
    private javax.swing.JComboBox<String> comboboxRas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField losenord;
    private javax.swing.JTextField namn;
    private javax.swing.JLabel nuvarandeAlienID;
    private javax.swing.JTextField plats;
    private javax.swing.JTextField regdatum;
    private javax.swing.JTextField telefon;
    private javax.swing.JButton uppdateraAlien;
    private javax.swing.JButton uppdateraRas;
    private javax.swing.JButton visaUppgifter;
    // End of variables declaration//GEN-END:variables
}
