/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.projektet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author oskarjolesjo
 */
public class Utrustning extends javax.swing.JFrame {
    private final String agentID;
    private InfDB idb;
    /**
     * Creates new form Utrustning
     */
    public Utrustning(InfDB idb, String agentID) {
        initComponents();
        this.idb = idb;
        this.agentID = agentID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLaggTillUtrustning = new javax.swing.JButton();
        btnVisaUtrustning = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textRuta = new javax.swing.JTextArea();
        txtAngeUtrustning = new javax.swing.JTextField();
        lblSkrivInUtrustning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Kaiti SC", 1, 24)); // NOI18N
        jLabel1.setText("Utrustning");

        btnLaggTillUtrustning.setText("Lägg till utrustning");
        btnLaggTillUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillUtrustningActionPerformed(evt);
            }
        });

        btnVisaUtrustning.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        btnVisaUtrustning.setText("Visa befintlig utrustning");
        btnVisaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaUtrustningActionPerformed(evt);
            }
        });

        textRuta.setColumns(20);
        textRuta.setRows(5);
        jScrollPane1.setViewportView(textRuta);

        txtAngeUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngeUtrustningActionPerformed(evt);
            }
        });

        lblSkrivInUtrustning.setText("Skriv in utrustning:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(lblSkrivInUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLaggTillUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAngeUtrustning))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisaUtrustning)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAngeUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSkrivInUtrustning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaggTillUtrustning)
                .addGap(24, 24, 24)
                .addComponent(btnVisaUtrustning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaUtrustningActionPerformed
        textRuta.setText("");
        ArrayList<String> allUtrustning;
        try {
           
            String sqlFraga = "select Benamning from Utrustning join Innehar_Utrustning IU on Utrustning.Utrustnings_ID = IU.Utrustnings_ID where Agent_ID ='" +agentID + "'";
            allUtrustning = idb.fetchColumn(sqlFraga);

            for (String utrustning : allUtrustning) {
                textRuta.append(utrustning + "\n");
            }
        } catch (InfException e) {
            System.out.println("fel" + e.getMessage());

        }
    }//GEN-LAST:event_btnVisaUtrustningActionPerformed

    private void btnLaggTillUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillUtrustningActionPerformed
//  
        String utrustningsId = txtAngeUtrustning.getText();
        
    try {
        String sqlFragaFinnsUtrustning = "SELECT * FROM utrustning WHERE benämning = '" + utrustningsId + "'";
        
        if (idb.fetchSingle(sqlFragaFinnsUtrustning) != null){
            JOptionPane.showMessageDialog(this, "Utrustningen har lagts till i din lista.");
        } else {
             JOptionPane.showMessageDialog(this, "Kan inte hitta utrustningstyp. Kontrollera stavningen.");
        }
        String sqlFraga = "INSERT INTO innehar_utrustning (this.agentID) VALUES ('" + utrustningsId + "')";
        idb.insert(sqlFraga);
        
    } catch (InfException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ett fel uppstod: " + e.getMessage());
    }
//        String utrustningsNamn = txtAngeUtrustning.getText();
//
//        try {
//
//            String sqlFragaFinnsUtrustning = "SELECT * FROM utrustning WHERE benämning = " + utrustningsNamn;
//            if (idb.fetchSingle(sqlFragaFinnsUtrustning) equals.utrustningsNamn) {
//                idb.insert(sqlFraga);
//                JOptionPane.showMessageDialog(this, "Alien har lagts till i databasen.");
//            }
//            
//                ); {
////                JOptionPane.showMessageDialog(this, "Alien-id finns redan i databasen.");
//                
//        String sqlFraga = "INSERT INTO innehar_utrustning (Benamning) "
//                        + "VALUES ('" + utrustningsNamn + "')";
//
//                
//
//            }catch (InfException e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Ett fel uppstod: " + e.getMessage());
//       
//       
//       } 
    }//GEN-LAST:event_btnLaggTillUtrustningActionPerformed

    private void txtAngeUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngeUtrustningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngeUtrustningActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillUtrustning;
    private javax.swing.JButton btnVisaUtrustning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSkrivInUtrustning;
    private javax.swing.JTextArea textRuta;
    private javax.swing.JTextField txtAngeUtrustning;
    // End of variables declaration//GEN-END:variables
}
